Progress on xml to son parser
cyclus/cyclus_gui pull request #5
Opened 2024-11-08 02:51 UTC by GersonEsquivel

Improved automatic template generation for autocompletion mechanism. Current code also saves output files on user's specified directory.

2024-11-10 22:35 UTC, gonuke requested changes
Not a lot of comments here.  I think it looks OK so far, but anticipate a big review when it's closer to being done.

2024-11-10 22:35 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
>      for facility_name, facility_config in processed_facilities.items():
Given all the repetition here, you could instead do:
```
    for agent_type, agent_list in zip(['facility', 'institution', 'region'], 
                                      [processed_facilities, processed_instutitions, processed_regions]):
        if agent_type in final_json["simulation"]:
            for agent_name, agent_config in agent_list.items():
                if agent_name in final_json["simulation"][agent_type]["config"]["ChildAtMostOne"]:
                    new_agent_config = {"InputTmpl": f'"{agent_name}", "MaxOccurs": 1}
                    new_agent_config.update(agent_config)
                    final_json["simulation"][agent_type]["config"][agent_name] = new_agent_config
````

2024-11-10 22:35 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +    matching_keys = [key for key in annotations.keys() if key.split(":")[-2] == key_name.split("_")[-3] and key.split(":")[-1] == key_name.split("_")[-1]]
I think this will be more readable if we define the following with variables first:
* `key_name.split("_")[-3]`
* `key_name.split("_")[-1]`

2024-11-11 22:56 UTC, GersonEsquivel commented
Done! I reduced the repetition (very nice structure), and added variables to improve readability.

2025-02-03 02:02 UTC, gonuke requested changes
I've requested a few changes here.  It's a lot of code to review and I wish we could have done it in more pieces.

I think it would help to have a lot more comments because the specialized knowledge you are acquiring is not clear from the code (and may never be from the code alone). On the other hand, there may be value in more modularity/functions that help describe things instead of comments, in some places.

2025-02-03 02:02 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +    def highlight_maker(self, name, word, color='blue'):
I think we can add `bold` and `italic` as function parameters and then use it to set the right characteristics of a rule

2025-02-03 02:02 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +        # highlight_str += highlight_maker('square_close', ']', 'lime')
Did you comment these out?  Might be good to put them back in.

2025-02-03 02:02 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +'''
Can't we use the `highlight_maker` function for these? especially if we extend it to support italics and add more colors to the color list

2025-02-03 02:02 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
>              return f"[{' '.join(facilities)}]", {}
Seems like this could be a little function since we reuse it in all three cases.

2025-02-03 02:02 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +    for agent_type, agent_list in zip(['facility', 'region'], [processed_facilities, processed_regions]):
It might be safer/more readable to manually bind/zip these since there will only ever be two:
```suggestion
    for agent_type, agent_list in [ ('facility, processed_facilities), ('region', processed_regions) ]:
```

2025-02-09 00:32 UTC, GersonEsquivel commented on XML_to_SON/grammar_parser_test.py
> +        # highlight_str += highlight_maker('square_close', ']', 'lime')
These were commented out by Jin Wan. I uncommented it to add them to the highlighter, but the items don't get highlighted. I tried multiple times to see if I was doing something wrong, but it appears that they are not recognized as elements that can be highlighted.

2025-02-16 01:19 UTC, gonuke commented on XML_to_SON/grammar_parser_test.py
> +save_template_for_all_schemas(processed_institutions, cyclus_metadata["annotations"], final_result_detailed_schemas["simulation"],template_dir)
These probably shouldn't be at global scope, but maybe inside the main function?

2025-02-18 19:26 UTC, GersonEsquivel commented on XML_to_SON/grammar_parser_test.py
> +save_template_for_all_schemas(processed_institutions, cyclus_metadata["annotations"], final_result_detailed_schemas["simulation"],template_dir)
Moved them. I don't know why they were like that.

2025-06-08 16:52 UTC, gonuke commented
Merging this in order to do some refactoring/streamlining

2025-06-08 16:52 UTC, merged